### ISSUE TITLE
No available to use with Laravel 5.6

### ISSUE THREAD

**Issue by p4scu41** [ahsankhatri/wordpress-auth-driver-laravel#1]
In the composer.json it requires Laravel 5.4.*, Is it possible to use it with Laravel 5.6?

**Comment by Galironfydar** [comment]
I've successfully got this working with Laravel 5.6 by forking the repository and updating the `composer.json` to `5.6.*`.

**Comment by p4scu41** [comment]
Thanks, I'll do that.

**Comment by ahsankhatri** [comment]
Support added. Closed.
