### ISSUE TITLE
Username instead?

### ISSUE THREAD

**Issue by MACscr** [ahsankhatri/wordpress-auth-driver-laravel#11]
Is it possible for us to easily use the default wordpress logins instead? Im a bit confused why it says this is for using with wordpress auth, but then doesnt even use the wordpress username, which is not typically an email address.

**Comment by ahsankhatri** [comment]
If I read it correctly, its Wordpress Auth integration into **LARAVEL** project, not the other way round.

**Comment by MACscr** [comment]
@ahsankhatri it is use the wordpress auth information (its pulling that data from the WP database) to allow you to use that same auth information to login to your laravel project. I just find it odd that it only pulls the email/password and forces you to use the email address in WP versus the actual username in WP that it could easily use instead. Get what I mean?

**Comment by ahsankhatri** [comment]
You can pass your field name as key in input array, So if you want to authenticate via username and password use following procedure:

```php
Auth::guard('wordpress')->attempt([
    'user_login' => 'johnny',
    'user_pass' => 'quickbrownfox'
]);
```

**Comment by MACscr** [comment]
Ah, i see where the confusion is. I setup the guard as the default in auth.php so i can use it to simply work as the general auth system for the laravel project. So in auth.php, i have:

```
    'defaults' => [
        'guard' => 'wordpress',
        'passwords' => 'wordpress',
    ],
```

and then in a route, im using:

```
Route::get('/sync_series', 'SyncController@sync_series')->middleware('auth');
```

**Comment by ahsankhatri** [comment]
Alright, for that you first need to publish config file via:

```bash
php artisan vendor:publish --provider="MrShan0\WordpressAuth\WordpressAuthServiceProvider"
```

And make changes in `config/wordpress-auth.php` wtih email_column to user_login
```php
'email_column' => 'user_login',
```

Most importantly, make sure you've used `<input name="email">` in your login page, that will override authentication criteria with `user_login` as specified in auth file. Because Laravel uses default field email for authentication.

**Comment by ahsankhatri** [comment]
Assuming this issue has been resolved. Closing.
