### ISSUE TITLE
Separate WP database

### ISSUE THREAD

**Issue by wespiremedia** [ahsankhatri/wordpress-auth-driver-laravel#2]
In my case, I want to use a separate DB for the WP tables and the Laravel tables. 

Because this provider uses an Eloquent model, this can be specified in the Model by: 
`protected $connection = 'mysql-wp';`

In `config/database.php` you can set-up an separate DB connection. 

You can copy the Model from the `vendor` to your `app` directory and inject the line above in the model. 

Maybe this is a nice feature to make configurable or add this to the readme?

**Comment by ahsankhatri** [comment]
Support added for separate connection. Closed.
